### ISSUE TITLE
   onTag: (tag) {} this function doesn't return first tag entered

### ISSUE THREAD

**Issue by amani27** [eyoeldefare/textfield_tags#1]
I tried getting tags, and noticed that the first tag entered is never returned? Why so?

**Comment by eyoeldefare** [comment]
Nice catch, I don't know how this could have scaped me since I have tested this before. I will fix this soon.

**Comment by eyoeldefare** [comment]
All fixed.

**Comment by amani27** [comment]
> All fixed.

works now, thanks for the quick response.
