### ISSUE TITLE
add nodefocus field for textfield widget.

### ISSUE THREAD

**Issue by hiru-vn** [eyoeldefare/textfield_tags#10]

**Comment by eyoeldefare** [comment]
what for?

**Comment by hiru-vn** [comment]
so developer can let other widgets know when the textfield is focus/unfocus.

**Comment by eyoeldefare** [comment]
> so developer can let other widgets know when the textfield is focus/unfocus.

The textfield states are being maintained internally, how do you suppose we expose the nodefocus property for outside widgets up the tree?
