### ISSUE TITLE
if the tag is only one word you get out of array bound..

### ISSUE THREAD

**Issue by TheKikeros** [eyoeldefare/textfield_tags#12]
https://github.com/eyoeldefare/textfield_tags/blob/822970a7f498ac2302d5b12b8f11ed4be9a4a63a/lib/src/main.dart#L184

**Comment by TheKikeros** [comment]
suggested fix:
```
onChanged: (value) {
        var splitedTagsList = value.split(" ");
 if(splitedTagsList.length <= 1)return;
.
.
.
```

**Comment by eyoeldefare** [comment]
hey sorry for the late reply, I am not experiencing the issue you outlined, tell me the OS and version you're running.

**Comment by TheKikeros** [comment]
big sur 11.1
but i don't think it is OS related, look at the code, if the list contain only one word you get (splitedTagsList.length - 2 = -1)

**Comment by eyoeldefare** [comment]
I am still not reproducing your issue and I don't see anyone having this problem. Give me the parameters you're feeding into the widget so I can reproduce the problem.

**Comment by eyoeldefare** [comment]
By the way, when I asked for version, I was talking about the version of this package `textfield_tags`. Anyhow, update the package to latest version, if you have not done so.
