### ISSUE TITLE
Error thrown RangeError (index): Invalid value: Only valid value is 0: -1

### ISSUE THREAD

**Issue by Gunnar-Stunnar** [eyoeldefare/textfield_tags#18]
https://github.com/eyoeldefare/textfield_tags/blob/bc1385f06e80e89b1ad67c8de63c606f6f726d0d/lib/src/main.dart#L183

This should be "-1" not "-2"

**Comment by eyoeldefare** [comment]
What version of this package are you running?
The reason I ask you that is so I can reproduce your error in my environment. My understanding is, there is a reason why I have it like that and I have tested everything before. So, for me to debug this, I need your version and the parameters you're using inside the widget.

**Comment by ShubhamHande99** [comment]
onChanged: (value) {
        var splitedTagsList = value.split(" ");
      
     // check if the spiltedTagsList length is not equal to 1
        if(splitedTagsList.length!=1){

           var lastLastTag =
            splitedTagsList[splitedTagsList.length - 2].trim().toLowerCase();

            print( splitedTagsList[splitedTagsList.length - 2].trim().toLowerCase());

        if (value.contains(" ")) {
          if (lastLastTag.length > 0) {
            _textEditingController.clear();

            if (!_tagsStringContent.contains(lastLastTag)) {
              widget.onTag(lastLastTag);

              if (!_showPrefixIcon) {
                setState(() {
                  _tagsStringContent.add(lastLastTag);
                  _showPrefixIcon = true;
                });
              } else {
                setState(() {
                  _tagsStringContent.add(lastLastTag);
                });
              }
              this._animateTransition();
            }
          }
        }

        }
        
       
      },

**Comment by ShubhamHande99** [comment]
════════ Exception caught by widgets ═══════════════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown while calling onChanged:[39;49m
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 108 pos 12: '_positions.isNotEmpty'


[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      ScrollController.position[39;49m
[38;5;248m#3      _TextFieldTagsState._animateTransition[39;49m
[38;5;248m#4      _TextFieldTagsState.build.<anonymous closure>[39;49m
[38;5;244m#5      EditableTextState._formatAndSetValue[39;49m
[38;5;244m#6      EditableTextState.updateEditingValue[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m


to fix this issue 
Wrap your _scrollController inside WidgetsBinding.instance.addPostFrameCallback 

 void _animateTransition() {
    var _pw = _deviceWidth;

    WidgetsBinding.instance.addPostFrameCallback((_){
    _scrollController.animateTo(
      _pw + _scrollController.position.maxScrollExtent,
      duration: const Duration(seconds: 3),
      curve: Curves.easeOut,
    );
  });
    
    
  }

**Comment by eyoeldefare** [comment]
I will ask you what I asked the first guy the same question: what version of this package are you running and the parameters you've used to get the errors. If you can't provide that, I can't help you.

**Comment by Gunnar-Stunnar** [comment]
Hi sorry for the late reply, at the time I ran this I was using the latest from Pub.dev

**Comment by kherel** [comment]
https://github.com/eyoeldefare/textfield_tags/pull/23

**Comment by eyoeldefare** [comment]
Fixed
