### ISSUE TITLE
Multiline input field

### ISSUE THREAD

**Issue by hermitty** [eyoeldefare/textfield_tags#19]
Is there any way to make the input field multiline?

**Comment by eyoeldefare** [comment]
I will look into this very soon.

**Comment by eyoeldefare** [comment]
I will look into this very soon

**Comment by eyoeldefare** [comment]
Hey, so I checked it out and theoretically its possible to implement something like that, however, it would require a redesign from the start and changing a couple of things. Unfortunately, I don't have the time to do that but I am open to merge anyone whose willing to work on it. Thanks

**Comment by chainchelliah** [comment]
Redesign? What are the changes required?

**Comment by eyoeldefare** [comment]
> Redesign? What are the changes required?

I don't know exactly but utilizing custom controllers, you can make this concept very much possible. Downside is it takes time and complications.
