### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by Neicul123** [eyoeldefare/textfield_tags#20]
Hi!

First, thanks for the great package! 

I was just wondering if a new version with null-safety support is on the way?

**Comment by eyoeldefare** [comment]
Hi, what do you mean by null-safety? As in entering null in the text-field?

**Comment by Neicul123** [comment]
Thanks for the quick response.

Flutter 2.0 has introduced null-safety features:

https://flutter.dev/docs/null-safety
https://dart.dev/null-safety/understanding-null-safety

The last link in particular explains what it is and why it is beneficial.

It basically has to do with error handling and requires a few syntax changes to the code. It seems like this will become the norm from v2.0 onwards and needs to be supported by packages in the future.

They (Flutter team) have a video where someone showcases how to migrate an existing app to make use of the null-safety features in 2.0, but mention that every dependency should be upgraded to a null-safety supporting version as well before migrating your app.

According to the associated command this package does not yet support it:
![image](https://user-images.githubusercontent.com/7229394/116313714-65dc0c00-a7ae-11eb-8ca8-e2c16f9b559f.png)

**Comment by eyoeldefare** [comment]
Oh I see, I will be honest with you, I haven't been working with Flutter for almost a year or so properly and don't know what is going on that much. 
I will pick up everything after the month of May as I will have more free time from backend work to start maintaining things properly and also creating other packages hopefully.

**Comment by eyoeldefare** [comment]
Thanks for the heads up, all done.
