### ISSUE TITLE
Costume tag delimeter

### ISSUE THREAD

**Issue by ecntu** [eyoeldefare/textfield_tags#25]
Hi,
I was wondering if support for costume delimeters, instead of only using spaces, is a feature you are looking to implement. I believe you just have to modify the onChanged in the TextField on main.dart to split value on a costume character. It would be really useful to have users separate tags with comas.
Thank you!

**Comment by eyoeldefare** [comment]
Hey, yeah I think we can do something like that. `if onCommaSeperateEnable? 'seperateOnComma':'dontSeperateOnComma' `; Or even separating on a comma seem a good idea in on itself. I will see to this very soon.
