### ISSUE TITLE
Duplicating tags when used inside a stepper

### ISSUE THREAD

**Issue by SyafiqI** [eyoeldefare/textfield_tags#26]
Version used: textfield_tags: ^1.3.1

When used in conjunction with a stepper with the type set to horizontal, the tags seem to be duplicating. However, when using its default type (type: StepperType.vertical), everything is working as intended.

This issue also occurs in flutter web

To recreate this issue:
 - Click continue to go to the next step
 - Input any number of tags (I did 1, 2, 3 but this issue occurs with any lists of Strings)
 - Click on the previous tab by clicking the number at the top of the stepper
 - Click continue to go to the next step
 - Enter any tags

Following these steps will have both the List<String> and the tags to contain duplicate values.

Loving the simplicity of the package, please do let me know of any updates on this issue and whether or not this issue arises either from the package or from Flutter itself. Thank you!

Here is a simple code that you can use to replicate the issue:

```
import 'package:flutter/material.dart';
import 'package:textfield_tags/textfield_tags.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Package Stepper/Tag'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> tagsListString = [];
  int currentStep = 0;

  void showInSnackBar(String value) {
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(value),
      duration: const Duration(seconds: 1),
    ));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Stepper(
          currentStep: currentStep,
          type: StepperType.horizontal,
          onStepContinue: () {
            print("next");
            if (currentStep < 2) {
              setState(() {
                currentStep++;
              });
            } else
              showInSnackBar("Complete!");
          },
          onStepCancel: () {
            print("reset");
            setState(() {
              currentStep = 0;
            });
          },
          onStepTapped: (index) {
            setState(() {
              currentStep = index;
            });
          },
          steps: [
            Step(isActive: true, content: TextField(), title: Text("Step 1")),
            Step(
                isActive: currentStep >= 1 ? true : false,
                content: TextFieldTags(
                    initialTags: tagsListString,
                    textFieldStyler: TextFieldStyler(
                      helperText: "Enter Tags Here",
                      hintText: "Example: 123 | abc",
                      textFieldFilledColor: Colors.white,
                    ),
                    tagsStyler: TagsStyler(
                        tagDecoration: BoxDecoration(color: Colors.blue),
                        tagTextStyle: TextStyle(color: Colors.white),
                        tagCancelIcon: const Icon(Icons.cancel,
                            size: 18.0, color: Colors.white)),
                    onTag: (tag) async {
                      print("adding $tag");
                      tagsListString.add(tag);
                      print("this is the new list: $tagsListString");
                    },
                    onDelete: (tag) {
                      print("deleting $tag");
                      tagsListString.remove(tag);
                      print("this is the new list: $tagsListString");
                    },
                    validator: (tag) {
                      if (tag!.length > 15) {
                        return "hey that's too long";
                      }
                      return null;
                    }),
                title: Text("Step 2")),
            Step(
                isActive: currentStep >= 2 ? true : false,
                content: Container(
                  width: MediaQuery.of(context).size.width,
                  height: MediaQuery.of(context).size.height,
                  child: ListView(
                    children: [
                      Text("This is the final list: "),
                      ...tagsListString.map((e) => Text(e))
                    ],
                  ),
                ),
                title: Text("Step 3")),
          ],
        ),
      ),
    );
  }
}
```

**Comment by eyoeldefare** [comment]
This is a very interesting scenario. This is one of those things where state management is important. 

The reason you're getting this error is because you're setting the initial tags `initialTags` with your own list of tags every time you switch steps (and this would have been okay if not for `Step` widget retained its state when it changes from page to page) but because the `Step` widget state is lost whenever you switch from one step to another, that means, you're starting a new `TextFieldTags` instance every time you come back to the 2nd step. This means, the `TextFieldTags` widget internally can't remove the duplicate tags because you're starting a new instance of the `TextFieldTags`. 

This is why when you come back to the 2nd step from the 3rd step, the previous `TextFieldTags` instance has been destroyed along with the previous `Step` widget. I hope I made it clear. Any questions are appreciated.
Also, this is the kinda reasons you would want to use maybe the `Provider' package to manage the states when you switch Steps.

So there is 2 options you have:

1. Empty the `tagsListString` list everytime you switch steps because that means the previous TextFieldTags() widget has been destroyed.
2. Use some sort of state-management. Flutter recommends the Provider package

**Comment by eyoeldefare** [comment]
Hey, first of all, thank you for exposing this bug. I thought this was a state-managment issue but this is an issue with `initialTag`. You see, `initialTag` is designed for final string data, it doesn't do well with variables. I didn't make that clear but I think I will roll out a new release making it compatible with both variables and final data.
For now, you can get away with `initialTag` = ['some string data']

**Comment by eyoeldefare** [comment]
Hey, first of all, thank you for shinning light to this issue. I thought this was a state-managment issue but this is also an issue with `initialTag` here. You see, `initialTag` is designed for a final string data in mind. The issue in this case is when you change the `initialTag` by adding `onTag` to it, the data we're receiving internally is the initial tags plus the new `onTag` value. That means, we're registering it twice internally in this case. Once when you call the `onTag`  on `tagsListString` and the other on the `onTag` function itself. So we're receiving ['some string'] +'some string'. This is not how this package was design for. The 'initialTag' can't be changed. They're final for every new instance of `TextFieldTags` widget. 

I think the best solution to this problem is to simply manage the tags in such a way that doesn't alter the `initialTag` value within your state class.

**Possiable Solution:** 

`

      class _MyHomePageState extends State<MyHomePage> {
          List<String> tagsListString = [], _initialTags = []; //Here we want to keep these seperate so you don't conflict with initial tags
          int currentStep = 0;
          void showInSnackBar(String value) {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(
              content: Text(value),
              duration: const Duration(seconds: 1),
            ));
          }

          @override
          Widget build(BuildContext context) {
            return Scaffold(
              appBar: AppBar(
                title: Text('widget.title'),
              ),
              body: Container(
                padding: const EdgeInsets.all(12.0),
                child: Stepper(
                  currentStep: currentStep,
                  type: StepperType.horizontal,
                  onStepContinue: () {
                    print("next");
                    if (currentStep < 2) {
                      setState(() {
                        currentStep++;
                      });
                    } else
                      showInSnackBar("Complete!");
                  },
                  onStepCancel: () {
                    print("reset");
                    setState(() {
                      currentStep = 0;
                    });
                  },
                  onStepTapped: (index) {
                    setState(() {
                      _initialTags = tagsListString;  //Here save the tags value in class property so you retain the values. Then set it when new instance of the widget is created 
                      tagsListString = []; //Here also set to [] because, next Step means, the previous widget state has been lost. Start new.
                      currentStep = index;
                    });
                  },
                  steps: [
                    Step(isActive: true, content: TextField(), title: Text("Step 1")),
                    Step(
                        isActive: currentStep >= 1 ? true : false,
                        content: TextFieldTags(
                            initialTags: _initialTags,
                            textFieldStyler: TextFieldStyler(
                              helperText: "Enter Tags Here",
                              hintText: "Example: 123 | abc",
                              textFieldFilledColor: Colors.white,
                            ),
                            tagsStyler: TagsStyler(
                                tagDecoration: BoxDecoration(color: Colors.blue),
                                tagTextStyle: TextStyle(color: Colors.white),
                                tagCancelIcon: const Icon(Icons.cancel,
                                    size: 18.0, color: Colors.white)),
                            onTag: (tag) async {
                              print("adding $tag");
                              tagsListString.add(tag);
                              print("this is the new list: $tagsListString");
                            },
                            onDelete: (tag) {
                              print("deleting $tag");
                              tagsListString.remove(tag);
                              print("this is the new list: $tagsListString");
                            },
                            validator: (tag) {
                              if (tag.length > 15) {
                                return "hey that's too long";
                              }
                              return null;
                            }),
                        title: Text("Step 2")),
                    Step(
                        isActive: currentStep >= 2 ? true : false,
                        content: Container(
                          width: MediaQuery.of(context).size.width,
                          height: MediaQuery.of(context).size.height,
                          child: ListView(
                            children: [
                              Text("This is the final list: "),
                              ...tagsListString.map((e) => Text(e))
                            ],
                          ),
                        ),
                        title: Text("Step 3")),
                  ],
                ),
              ),
            );
          }
        }

`

**Comment by SyafiqI** [comment]
I see. Thank you for the quick response. Will implement these changes and will reply if there are any other comments to be made in the future. For now, will close the comment. Thanks again!
