### ISSUE TITLE
Max Tags property

### ISSUE THREAD

**Issue by diogosequeira94** [eyoeldefare/textfield_tags#27]
Hi, I can't find a property for max tags. Is there a way to expose a new tags limit? Or a better way to get the Tags List length so we can limit adding extra tags?

**Comment by eyoeldefare** [comment]
Hey, there is currently no way to do that from our side but you can easily do that from your application side. Since you're saving the tags inside a list in your app, you can check its length `list.length`.

**Comment by diogosequeira94** [comment]
Hi thanks for the comment.

The problem I'm facing has to do with TextFieldStyler property **textFieldEnabled**.

Even if I'm saving my tags in a List, I can check my list.length, and if its for example == 5 I can set textFieldEnabled to **false**.

The user now cannot add any more tags because the text field is disabled, but the tags cannot be removed by clicking the X icon. 

Do you see any good way to counter this? Maybe adding a 'remove button' and pop the last tag from the list?

**Comment by eyoeldefare** [comment]
Not entirely understand the issue but I will try to add some sort of constraining property to address the overall issue soon.

**Comment by eyoeldefare** [comment]
I get what you mean now, this can be resolved by using `setState` the moment the user reaches the limit of tags. Forexample, if you don't want user to enter no more than 5 tags, the moment tags reach 5, you set the disable property on the textfield.

**Comment by minhdanh** [comment]
Hi @diogosequeira94, could you find a solution for your problem?

**Comment by CodeFoxLk** [comment]
@diogosequeira94 

try readOnly in textfield

`inputFieldBuilder: (context, tec, fn, error, onChanged, onSubmitted) {
            return ((context, sc, tags, onTagDelete) {
              return TextField(
                controller: tec,
                focusNode: fn,
                readOnly: tags.length >= 5,`
