### ISSUE TITLE
How to fire onchange event

### ISSUE THREAD

**Issue by MohitPainuly17** [eyoeldefare/textfield_tags#28]
Hello, I got an issues of index out of range issues while input text to make a tag, but before tag creation, it shows errors of index out of range

**Comment by eyoeldefare** [comment]
Please provide me with more details so i can reproduce your error in my environment.

**Comment by bgetsug** [comment]
I believe this issue has to do with using `TextFieldTags` without a validator:

```dart
TextFieldTags(
  tagsStyler: TagsStyler(
    tagDecoration: BoxDecoration(color: Colors.blue),
  ),
  textFieldStyler: TextFieldStyler(
    textFieldFilled: true,
    hintText: "Tags",
    helperText: null,
    textFieldBorder: OutlineInputBorder(borderSide: BorderSide.none),
  ),
  onTag: (tag) {
    //todo
  },
  onDelete: (tag) {
    //todo
  },
)
```

Upon entering a tag, I received an exception: `Null check operator used on a null value`

![Screen Shot 2021-07-11 at 4 39 54 PM](https://user-images.githubusercontent.com/1869022/125210722-37c37f80-e267-11eb-91e7-01ace477913c.png)
