### ISSUE TITLE
Display a dropdown below textfield

### ISSUE THREAD

**Issue by mohamad-elbohsaly** [eyoeldefare/textfield_tags#29]
Can I display a drop-down menu upon typing a tag?
Similar to:
![Screen Shot 2021-06-28 at 10 31 10 PM](https://user-images.githubusercontent.com/18421260/124025451-1f4a9e00-d9f9-11eb-9864-bee191e6c34d.png)

**Comment by eyoeldefare** [comment]
This is something you need to try and experiment yourself.
