### ISSUE TITLE
Exception when validator is null

### ISSUE THREAD

**Issue by bgetsug** [eyoeldefare/textfield_tags#31]
I tried to use `TextFieldTags` without a validator:

```dart
TextFieldTags(
  tagsStyler: TagsStyler(
    tagDecoration: BoxDecoration(color: Colors.blue),
  ),
  textFieldStyler: TextFieldStyler(
    textFieldFilled: true,
    hintText: "Tags",
    helperText: null,
    textFieldBorder: OutlineInputBorder(borderSide: BorderSide.none),
  ),
  onTag: (tag) {
    //todo
  },
  onDelete: (tag) {
    //todo
  },
)
```

Upon entering a tag, I received an exception: `Null check operator used on a null value`

![Screen Shot 2021-07-11 at 4 39 54 PM](https://user-images.githubusercontent.com/1869022/125210843-d9e36780-e267-11eb-9b5a-743126e3f8d5.png)

**Comment by eyoeldefare** [comment]
I will look into this tomorrow, thanks for the heads up.
