### ISSUE TITLE
Want to set icon on the left/right side

### ISSUE THREAD

**Issue by myConsciousness** [eyoeldefare/textfield_tags#32]
Hi, thanks for this amazing development.

I want to set icon on the left/right side of the widget created by TextFieldTags, and is this supported by this class?
I want it to create like the following image.

<img width="469" alt="スクリーンショット 2021-07-12 13 43 04" src="https://user-images.githubusercontent.com/13072231/125232273-381b5380-e317-11eb-881f-71cdd93b5465.png">

I could simply implement it myself with Icon widget,
but if the functionality is supported by this class, I would prefer to use it.

**Comment by eyoeldefare** [comment]
Thanks for this issue and contributing
