### ISSUE TITLE
One tag I enter will be entered twice as hashtag

### ISSUE THREAD

**Issue by myConsciousness** [eyoeldefare/textfield_tags#36]
Hello, I have reproduced a bug related to #17 which has already been closed!

I'm using the latest version and the codes are below.

```dart
Flexible(
  child: TextFieldTags(
    initialTags: this._task.tags, // It happens when I set this option.
    onTag: (String tag) {
      this._tags.add(tag);
    },
    onDelete: (String tag) {
      this._tags.remove(tag);
    },
  ),
),
```

And these photos are what happened.

<img width="451" alt="スクリーンショット 2021-07-31 22 17 26" src="https://user-images.githubusercontent.com/13072231/127741333-72963b1d-b22d-482f-bd44-f8bbfe1962dc.png">

<img width="464" alt="スクリーンショット 2021-07-31 22 17 35" src="https://user-images.githubusercontent.com/13072231/127741340-55293ecb-ef64-4a1d-836b-893a8fac2c38.png">

**Comment by eyoeldefare** [comment]
Hey yeah I remember this issue, if I recall correctly, the `initialTags` must be **final**.

Edit: 
You can't alter the `initialTags` after provided to the widget. They must be final. The reason is, internally, they conflict with our own tags and creates this bug you see.

**Comment by myConsciousness** [comment]
Hi @eyoeldefare !

I understand the situation from your explanation.
The problem was solved when I copied the list specified in `initialTags` to the list that is not changed during processing.

But it was difficult to understand why this happened at first, so I thought it might be possible to copy the initial tag list received inside `TextFieldTags` as `final` .

**Comment by eyoeldefare** [comment]
Yeah, perhaps we can add comment telling users that `initialTags` must be final? Or somehow implement an exception when user changes the initial tags. I will look into this in the near future.

**Comment by eyoeldefare** [comment]
Actually there is a better way to solve this issue, I will look into it soon.
