### ISSUE TITLE
Cannot change keyboardType

### ISSUE THREAD

**Issue by taufik1207** [eyoeldefare/textfield_tags#37]
Hello, i want to change keyboardType. But, parameter not available

**Comment by eyoeldefare** [comment]
It's set to text by default since you're entering tags. If its necessary, it should be simple to make it available. But since this is tags, I don't see why you would need to change it to something else.

**Comment by vasilich6107** [comment]
@eyoeldefare it is easier to pass through all available pros to textfield and forget about this types of issues

**Comment by eyoeldefare** [comment]
You're right @vasilich6107 but many things changed since I last viewed the widget. Many properties also added.

**Comment by eyoeldefare** [comment]
Done
