### ISSUE TITLE
Textfield chips does not support multilines.

### ISSUE THREAD

**Issue by Govindbetterlives** [eyoeldefare/textfield_tags#38]
Hi guys, how can i set textfield chips in miltilines. anybody know that please reply. thanks.

![tag](https://user-images.githubusercontent.com/81243940/139851306-fbc69f1c-1aad-4241-868d-5682b9bbfe4a.png)

**Comment by zanpen2000** [comment]
same here, anybody ?

**Comment by eyoeldefare** [comment]
Multi lines are not supported.

**Comment by leeyisoft** [comment]
There is no support for multi-line function, feel that support for multi-line user input experience will be better

**Comment by hardiklakhalani** [comment]
@eyoeldefare @leeyisoft 
I'll try with my fork, if it'll work I'll add a PR.

**Comment by leeyisoft** [comment]
> @eyoeldefare @leeyisoft I'll try with my fork, if it'll work I'll add a PR.

@hardiklakhalani I took a look at the textfield_tags source code, it is difficult for me to add support multilines functionality, looking forward to your results

**Comment by hardiklakhalani** [comment]
@eyoeldefare  @leeyisoft  @Govindbetterlives 
It's not required by Package, it can be achieved by the user: Please See the Added Example PR https://github.com/eyoeldefare/textfield_tags/pull/77

**Comment by leeyisoft** [comment]
> @eyoeldefare @leeyisoft @Govindbetterlives It's not required by Package, it can be achieved by the user: Please See the Added Example PR #77

Thanks very much to the eyoeldefare/textfield_tags library and your @hardiklakhalani  demo  https://github.com/eyoeldefare/textfield_tags/pull/77 , I have implemented the function of line wrapping

Here is the key code：

scrollDirection: Axis.vertical,
```

                            prefixIconConstraints: BoxConstraints(
                                maxWidth: state.distanceToField * 1.0),
                            prefixIcon: tags.isEmpty
                                ? null
                                : SingleChildScrollView(
                                    controller: scController,
                                    scrollDirection: Axis.vertical,
                                    child: Wrap(
                                      // runSpacing: 7.0,
                                      children: (tags.map((String tag) {
                                        return TagItem(
```

Row(
        mainAxisAlignment: MainAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
```
import 'package:flutter/material.dart';

///
class TagItem extends StatelessWidget {
  final String tag;
  final Function(String tag) onTagDelete;

  final Color backgroundColor;
  final Color selectedBackgroundColor;
  final Color tagSelectedColor;

  const TagItem({
    Key? key,
    required this.tag,
    required this.onTagDelete,
    this.backgroundColor = const Color(0xfff8f8f8),
    this.selectedBackgroundColor = const Color(0xFF649BEC),
    this.tagSelectedColor = const Color(0xFF649BEC),
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        borderRadius: const BorderRadius.all(
          Radius.circular(20.0),
        ),
        color: selectedBackgroundColor,
      ),
      margin: const EdgeInsets.only(right: 10.0, top: 6, bottom: 6),
      padding: const EdgeInsets.symmetric(
        horizontal: 10.0,
        vertical: 4.0,
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          InkWell(
```
<img width="395" alt="image" src="https://github.com/eyoeldefare/textfield_tags/assets/6138668/9589fa99-028e-4d31-a7d0-c3b0f65c41f2">

**Comment by leeyisoft** [comment]
> @eyoeldefare @leeyisoft @Govindbetterlives It's not required by Package, it can be achieved by the user: Please See the Added Example PR #77

How do I position the cursor after the end？

![image](https://github.com/eyoeldefare/textfield_tags/assets/6138668/1cfec8d7-2b57-4476-85ac-64b0b4a714bc)

**Comment by hardiklakhalani** [comment]
@leeyisoft I tried looking for solution but could not find a way. Chips as prefix widget & Textfield is not multiline that's why cursor stays in center. If we turn textfield to multiline, cursor can goes to top but that'll bring up tags with _line-breaks_

Let us know if you or anyone else can get through.

**Comment by leeyisoft** [comment]
> @leeyisoft I tried looking for solution but could not find a way. Chips as prefix widget & Textfield is not multiline that's why cursor stays in center. If we turn textfield to multiline, cursor can goes to top but that'll bring up tags with _line-breaks_
> 
> Let us know if you or anyone else can get through.

Okay, I found a way back here to share
