### ISSUE TITLE
clear / reset fields

### ISSUE THREAD

**Issue by Trend74X** [eyoeldefare/textfield_tags#40]
I have this TextFieldTags used inside a form. After the form is submitted, it is supposed to reset or clear the tags after successful submit. I dont see how to achieve this, or is there any way to do this?

**Comment by hardiklakhalani** [comment]
Yes, a `TextEditingController` would be helpful here (which is already implemented inside the widget with `controller.clear()` function but didn't bring it out in parameters).

**Comment by mark8044** [comment]
For sure we need a controller....

**Comment by mark8044** [comment]
I just made a PR that seems to work for me https://github.com/eyoeldefare/textfield_tags/pull/45

**Comment by eyoeldefare** [comment]
Thanks mark8044, I have merged your request.
