### ISSUE TITLE
Case Sensitivity feature?

### ISSUE THREAD

**Issue by hardiklakhalani** [eyoeldefare/textfield_tags#42]
It is TextFieldTags but it's obvious we are going to use it for any similar purpose other than small-case #hashtags.
So is there a way to keep TypeCase as it entered or TitleCase/Uppercase/Lowercase(which is the default/stubborn right now)

**Comment by eyoeldefare** [comment]
I think this could be possible to do using built in properties from textfield, I will have see to it.

**Comment by eyoeldefare** [comment]
Done
