### ISSUE TITLE
Autocomplete support

### ISSUE THREAD

**Issue by mark8044** [eyoeldefare/textfield_tags#46]
Autocomplete support would put this over the top in sheer awesomeness ...

**Comment by eyoeldefare** [comment]
I will actually see if I can implement this soon. Its a good suggestion.

**Comment by eyoeldefare** [comment]
Okay so I looked into it and its very much possible to do this from our-side but needs breaking changes. However, since we made the controller available to users now, you can easily make this happen from your side too.

**Comment by eyoeldefare** [comment]
Autocomplete now supported.
