### ISSUE TITLE
Can I put # in front of it?

### ISSUE THREAD

**Issue by chb1828** [eyoeldefare/textfield_tags#5]
I want to automatically put # in front of textfield_tags like #tag1 #tag2
and then Can I delete it when I put backspace button?
is this possible?
@eyoeldefare

**Comment by eyoeldefare** [comment]
I will see a way to implement the hashtag sometime in the future, but for the backspace, unfortunately, I don't really have the time to add the functionality and testing that needs to be done myself for now.

**Comment by chb1828** [comment]
@eyoeldefare 
thank you for the reply. It was very helpful.
