### ISSUE TITLE
Vertical scrollable tagfield ?

### ISSUE THREAD

**Issue by RageshAntony** [eyoeldefare/textfield_tags#53]
I implemented tags list using your library 

But the tags are scrolling horizontally . 

I need to scroll them vertically 

How to do this ?

And also how to add vertical and horizontal scrollbars and increase their size ?

Flutter Web 

1. Horizatnal scroll not working in flutter web and desktop when using scroll wheel of mouse !!!! ???
2. How to attach a scroll controller like TextField ?

**Comment by eyoeldefare** [comment]
I have tested this to work on flutter web, not sure whether scroll wheel of mouse works or not. 
Second, scroll controller is not accessible at this time.

**Comment by RageshAntony** [comment]
> I have tested this to work on flutter web, not sure whether scroll wheel of mouse works or not.
> Second, scroll controller is not accessible at this time.

I edited the project by cloning and added public scroll controller and now working with Wrapped scrollbar

**Comment by eyoeldefare** [comment]
Well done.
