### ISSUE TITLE
Limit the number of tags?

### ISSUE THREAD

**Issue by minhdanh** [eyoeldefare/textfield_tags#54]
Hi,
For some reason I need to limit the number of tags. How can I do that?

Thanks.

**Comment by eyoeldefare** [comment]
Yes, I will be adding this plus more functions soon.
Hopefully by tomorrow. Thanks

**Comment by eyoeldefare** [comment]
All done.

**Comment by minhdanh** [comment]
Hi @eyoeldefare,
I see this is closed, but looking at the README file I'm still not sure how to limit the number of tags. Can you please tell how to do that? :sweat_smile:
