### ISSUE TITLE
Breaking changes comming up after V2.0.0+ release (BE AWARE BEFORE UPDATING)

### ISSUE THREAD

**Issue by eyoeldefare** [eyoeldefare/textfield_tags#55]
Please note that the next release will be v2.0.0 and it will be breaking change. So if you update your package to v2+, it will break your code. The reason i am updating this package is to make it more robust and customizable and also to make it upto date with new features in flutter.

**Some of the things that will be implemented are:**

1. Custom autocomplete support by user as per issue #46 request 
2. Build your own custom widget instead of using our implementation
3. More functionality using custom controller

**Comment by Luppakorva** [comment]
Any chance for a detailed way to transfer from old version to new with this change? I must admit I'm quite lost how to get even the basic functionalities back up and running with the > 1.44. Would be awesome and surely help plenty, not just myself :). It's an awesome plugin in overall though and thank you for creating and updating it!

**Comment by lhengl** [comment]
I tinkered with the code locally and have found that the issue is due to the controller being initialised on the widget's initState. This is especially troublesome if you want to keep the controller in a state outside the widget itself. Essentially, if you have a ListView or PageView that disposes the widget, but keeping the controller alive somewhere else such as in a statement management solution (in my case GetxController). Took me a few tries, but the below code has now solved my problem:

main.dart
```
@override
  void initState() {
    super.initState();
    _ttc = widget.textfieldTagsController ?? TextfieldTagsController();
    if (!_ttc.isInitialised) {
      _ttc
        ..init(
          widget.validator,
          widget.letterCase,
          widget.initialTags,
          widget.textEditingController,
          widget.focusNode,
          widget.textSeparators,
        )
        ..scrollTags(forward: true);
    }

    _error = _ttc.getError;
    _tags = _ttc.getTags;

    _ttc.addListener(() {
      setState(() {
        _error = _ttc.getError;
        _tags = _ttc.getTags;
      });
    });
  }

```

controller.dart

```
  bool _isInitialised = false;
  bool get isInitialised => _isInitialised;

  TextfieldTagsController();

  void init(
    Validator? validator,
    LetterCase? letterCase,
    List<String>? initialTags,
    TextEditingController? tec,
    FocusNode? fn,
    List<String>? textSeparators,
  ) {
    super.initS(initialTags, tec, fn, textSeparators);
    _letterCase = letterCase ?? LetterCase.normal;
    _validator = validator;
    _isInitialised = true;
  }
```

**Comment by eyoeldefare** [comment]
Yeah its different from the previous version which is discontinued. The easy way is perhaps to simply use one of the examples: 
[this one](https://github.com/eyoeldefare/textfield_tags/blob/master/example/lib/main.dart) or [this one](https://github.com/eyoeldefare/textfield_tags/blob/master/example/lib/main1.dart)
