### ISSUE TITLE
How to avoid empty tag?

### ISSUE THREAD

**Issue by minhdanh** [eyoeldefare/textfield_tags#57]
Hi, is there a way to avoid this empty tag?

![image](https://user-images.githubusercontent.com/4865412/160270577-9366f2e1-6d77-4e1f-ba2f-d013042dc30c.png)

My text separators:
```
            textSeparators: const [' ', '.', ','],
```

**Comment by eyoeldefare** [comment]
Its for things like this you want to use the `validator` function provided. 
```javascript
   if (tag == '') {
       return 'no empty tags';
   }

```

**Comment by minhdanh** [comment]
Yeah, we can do that, but can we prevent the empty tag from being added from the first place? Right now whenever switch to another input, the empty tag is automatically created.

**Comment by eyoeldefare** [comment]
I don't know what that means. 
If you did as the above example, the tags shouldn't be added in the first place. 
For more, look at the api and how it works.

**Comment by motasimfuad** [comment]
@minhdanh did you find the solution?

**Comment by motasimfuad** [comment]
@eyoeldefare please take a look at the image.
I understand the solution with the validator. But I don't want to show any validation for that. 
Is that an issue with the trim() method? How do I fix that?![GridArt_20220410_153158610.jpg](https://user-images.githubusercontent.com/72114794/162612076-0b35c1b5-beaf-4ed9-9ab4-ed34118646c6.jpg)

**Comment by eyoeldefare** [comment]
The reason I didn't implement small things like that is to give developers the options to do what they want with this plugin. Remember guys, you can create your own controllers to recreate how tags should behave when they're created, stored, deleted, etc. 
I guess majority people seem to want to remove this space so I will remove it by next release.
