### ISSUE TITLE
warning after flutter 3.0

### ISSUE THREAD

**Issue by SainathChallagundla** [eyoeldefare/textfield_tags#58]
/C:/Users/Bala/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/textfield_tags-2.0.0+1/lib/src/controller.dart:86:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/Users/Bala/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addPostFrameCallback((_) {

after switched to flutter 3.0 and  textfield_tags 2.0.0+1 getting this warning.

**Comment by minhdanh** [comment]
Seeing this warning as well

**Comment by Deltap3** [comment]
I have this problem aswell and this is my PR to fix it ;) #59

**Comment by eyoeldefare** [comment]
Thanks @Deltap3 for the PR. I will merge this soon.
