### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SainathChallagundla** [eyoeldefare/textfield_tags#60]
/C:/Users/Bala/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/textfield_tags-2.0.0+1/lib/src/main.dart:56:13: Error: Too few positional arguments: 6 required, 5 given.
      ..init(
            ^
/C:/Users/Bala/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/textfield_tags-2.0.0+1/lib/src/main.dart:81:12: Error: The getter 'focusNode' isn't defined for the class 'TextfieldTagsController'.
- 'TextfieldTagsController' is from 'package:textfield_tags/src/controller.dart' ('/C:/Users/Bala/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/textfield_tags-2.0.0+1/lib/src/controller.dart').
package:textfield_tags/src/controller.dart:1

Try correcting the name to the name of an existing getter, or defining a getter or field named 'focusNode'.
      _ttc.focusNode!,
           ^^^^^^^^^
/C:/Users/Bala/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/textfield_tags-2.0.0+1/lib/src/controller.dart:69:16: Error: Too few positional arguments: 4 required, 3 given.
    super.initS(initialTags, tec,  textSeparators);
               ^
/C:/Users/Bala/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/textfield_tags-2.0.0+1/lib/src/controller.dart:83:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/Users/Bala/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^

/C:/Users/Bala/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/textfield_tags-2.0.0+1/lib/src/controller.dart:178:5: Error: The getter 'focusNode' isn't defined for the class 'TextfieldTagsController'.
- 'TextfieldTagsController' is from 'package:textfield_tags/src/controller.dart' ('/C:/Users/Bala/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/textfield_tags-2.0.0+1/lib/src/controller.dart').
package:textfield_tags/src/controller.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'focusNode'.
    focusNode!.dispose();
    ^^^^^^^^^

after switched to flutter 3.0.2 having this issue.
currently my app not working due to this issue.
I hope it will solve as soon as possible.

**Comment by eyoeldefare** [comment]
yeah, there is a pull request to address this issue. Its because of Flutter 3.0. I will upgrade it soon.

**Comment by SainathChallagundla** [comment]
> yeah, there is a pull request to address this issue. Its because of Flutter 3.0. I will upgrade it soon.

Thank you for the quick response.
