### ISSUE TITLE
null safety error

### ISSUE THREAD

**Issue by tekangun** [eyoeldefare/textfield_tags#63]
need to replace "!" to "?" character, It doesn't work because there is no question mark because there is a definition that can be null.

lib>src>controller.dart line 87
#60 #58

**Comment by eyoeldefare** [comment]
Were you able to catch where this exception was thrown? 
I just upgraded it to Flutter 3.0, and it passed my tests. If you perhaps post a snipped example would help me debug this. 
Thanks

**Comment by erkinyldz** [comment]
@eyoeldefare does the commit helps you?

**Comment by eyoeldefare** [comment]
Hey, no. 
They need to either upgrade to flutter 3.0 or downgrade the package most likely.

**Comment by eyoeldefare** [comment]
Feel free to reopen this if the new update doesn't fix this considering its the same issue as $63
