### ISSUE TITLE
Add custom data type support

### ISSUE THREAD

**Issue by ashishpipaliya** [eyoeldefare/textfield_tags#70]
Getting `'Instance of 'MasterData'` when I use `AutComplete<MasterData>`. see code below
![Screenshot 2022-08-19 at 11 49 23 AM](https://user-images.githubusercontent.com/32923529/185555656-7027947f-8d9f-4fd0-8376-ed7d93ff3424.png)

```dart
 optionsBuilder: (TextEditingValue textEditingValue) {
                                if (textEditingValue.text == '') {
                                  return const Iterable<MasterData>.empty();
                                }
                                return addNewProjectsProvider.serviceList.where((MasterData option) {
                                  return option.typeName!.contains(textEditingValue.text.toLowerCase());
                                });
                              },
```

After selecting any item, it shows name properly.
![Screenshot 2022-08-19 at 11 51 40 AM](https://user-images.githubusercontent.com/32923529/185555969-e1ecdacd-1f55-462c-97e2-5552b54d562e.png)

So, is there any way to change 'Instance of 'MasterData' to actual type(`MasterData.typeName`) ?

**Comment by eyoeldefare** [comment]
This has nothing to do with this package. This is happening because your object MasterData doesn't return a text object which is needed to be displayed by Autocompleter widget.

**Comment by eyoeldefare** [comment]
Our widget actually supports this now. But note AutComplete is not our widget
