### ISSUE TITLE
Overriding setAdd and onSubmitted doesn't work

### ISSUE THREAD

**Issue by diogosequeira94** [eyoeldefare/textfield_tags#78]
Tried to override _**setAdd**_ and **_onSubmitted_** on a CustomController to manage the onTag() callback and it doesn't seem to be working properly. On the opposite, overriding onChanged works fine.

Any clue on the issue?

**Comment by eyoeldefare** [comment]
Sorry for the late message but I will see to it this week. Thanks for the feedback

**Comment by eyoeldefare** [comment]
Here is an example of how you can override onSubmit or any question related to custom controller.
