### ISSUE TITLE
BorderStyle 

### ISSUE THREAD

**Issue by yubarajshrestha** [eyoeldefare/textfield_tags#8]
I would like to have a material look without border. I can I accomplish that? I want TextField's bottom border only and remove all others.

**Comment by eyoeldefare** [comment]
Sure, you can create any kind of TextField UI with it. It has all the properties of TextField so you should be able to create any TextField UI you want.

**Comment by eyoeldefare** [comment]
Perhaps this is what you want?
``` dart
      TextFieldStyler(
            textFieldBorder: null,
            isDense: false,
            hintText: "Tags",
            helperText: 'Add tags',
      ),
```

**Comment by yubarajshrestha** [comment]
@eyoeldefare  perfect. It worked. Thanks
