### ISSUE TITLE
Add text to tag when the focus is change to next Textfield

### ISSUE THREAD

**Issue by stefanwerfling** [eyoeldefare/textfield_tags#80]
When focus is passed to the next text field, how can I add the typed text as a tag? People enter in the text field that as soon as "," or " " comes it will be a tag. But the last entry remains as text and is then lost when saving.

You could say this is an operating error, but I would like to catch it!
![image](https://github.com/eyoeldefare/textfield_tags/assets/12471903/f5b4c734-05fb-4da2-8d5f-a43613e9354d)

**Comment by eyoeldefare** [comment]
Hey, I see you have opened many issues. I will officially look through all of them including any PR next week. Thanks for raising the issues.

**Comment by eyoeldefare** [comment]
Hey, the dispose exception is because we're disposing the focus and textfieldcontroller instance internally which is wrong on our side. The issue has been raised by others in the past but never really gotten the time to fix it. I will see to it this week finally.

**Comment by stefanwerfling** [comment]
I'm looking forward to it, then I can update the new version of my app and pass on the good news :)

**Comment by eyoeldefare** [comment]
Just pushed an update that fixed lots of issues mentioned by others. Thanks for the patience.
