### ISSUE TITLE
Tags not working

### ISSUE THREAD

**Issue by Aquarius-blake** [eyoeldefare/textfield_tags#84]
I tried using the example in the ReadMe , however it just displayed a normal text field.
There were no errors in the console either.

**Comment by eyoeldefare** [comment]
Someone also raised similar issue earlier. Please note that I provide you guys with an example in the example section of the code for this reason. The read me section doesn't show all the codes required to build a functional widget.

**Comment by Aquarius-blake** [comment]
Ok Thank you for your response
